### ISSUE TITLE
No x and y axis texts on basic chart

### ISSUE THREAD

**Issue by mzubiald** [hongyuanjia/ggpsychro#3]
Hello,
Trying to plot the psychrometric chart with the basic command line:
`ggpsychro(tdb_lim = c(0, 50), hum_lim = c(0, 50), units = "IP") `
I obtain the chart with no X and Y axis text. I do have axis title but no text indicating the X and Y axis values.
I know i can add it using `scale_x_continuous` but I don't know how to do it for the Y-axis on the right.
And above all, I would like to understand why it is not displayed by default in my case.
Thanks in advance.

**Comment by hongyuanjia** [comment]
Confirmed this bug. In ggplot2 v3.3.0, the axis system has been [rewritten](https://www.tidyverse.org/blog/2020/03/ggplot2-3-3-0/). I will make ggpsychro compatible with it and push a fix.

**Comment by hongyuanjia** [comment]
@mzubiald Shoud have fixed now. Please try the development via `remotes::install_github("hongyuanjia/ggpsychro")`

**Comment by mzubiald** [comment]
@hongyuanjia 
I confirm you that the bug has been fixed.
Thanks a lot
